import '../dto/error_code.dart';

/// Base class for all exceptions generated by Storage.
class StorageException implements Exception {
  final ErrorCode errorCode;
  final String message;

  StorageException(this.errorCode, this.message);

  @override
  String toString() => message;
}

/// Exception thrown when requested data is not found in storage.
class StorageNotFoundException extends StorageException {
  StorageNotFoundException(String message)
      : super(ErrorCode.notFoundError, message);
}
