import 'package:event/event.dart';

import '../dto.dart';

/// Base class for all events generated by Agent.
/// Since the class sealed, it is guaranted that all possible
/// implementations are listed in this file.
sealed class AgentEvent extends EventArgs {}

/// Generated when error happens in background.
class AgentErrorEvent extends AgentEvent {
  AgentErrorEvent(this.errorCode);

  final ErrorCode errorCode;
}

/// Generated when Agent state changes.
class AgentStateEvent extends AgentEvent {}
