import '../dto.dart';

/// Base class for all exceptions generated by Agent.
class AgentException implements Exception {
  final ErrorCode errorCode;
  final String message;

  AgentException(this.errorCode, this.message);

  @override
  String toString() => message;
}

/// Missing or rejected permission.
class AgentPermissionException extends AgentException {
  AgentPermissionException(String message)
      : super(ErrorCode.permissionError, message);
}
