name: build

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4

      - name: Install NDK
        run: sdkmanager --install "ndk;$(grep ndkVersion app/gradle.properties | cut -d= -f2)"

      - name: Build
        run: ./gradlew build

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4

      - name: Install NDK
        run: sdkmanager --install "ndk;$(grep ndkVersion app/gradle.properties | cut -d= -f2)"

      - name: Get release info
        id: get-info
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build
        run: ./gradlew build

      - name: Copy and rename binary
        run: cp app/build/outputs/apk/debug/app-debug.apk roc-droid-${{ env.VERSION }}.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: roc-droid-${{ env.VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
